name: SpringBoot CI

on: [ push ]

jobs:
  Build:
    name: test, build and extract layers
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots clean package -DskipTests
      - name: Upload jar
        uses: actions/upload-artifact@v3
        with:
          name: jar
          path: target/*.jar

  Docker-Image:
    name: build docker image
    needs: Build
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          buildkitd-flags: --debug
      - name: Download jar
        uses: actions/download-artifact@v3
        with:
          name: jar
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Extract jar layers
        run: cp *.jar app.jar && java -Djarmode=layertools -jar app.jar extract
      - name: Bake Docker Image
        run: |
          docker build -t myimage:latest --progress=plain --no-cache .
          docker image ls -a
      - name: Test
        run: docker image ls -a

      # - name: Build and push
      #   uses: docker/build-push-action@v4
      #   with:
      #     no-cache: true
      #     push: true
      #     tags: ${{ secrets.DOCKERHUB_USERNAME }}/widget-service:latest
